/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComponentList: typeof import('./src/components/ComponentList.vue')['default']
    CreateProject: typeof import('./src/components/CreateProject.vue')['default']
    GoBack: typeof import('./src/components/GoBack.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
